name: diskusi_bisnis_mobile
description: Aplikasi Mobile DiskusiBisnis (Flutter)
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  lucide_icons: ^0.257.0
  http: ^1.1.0
  intl: ^0.18.0
  shared_preferences: ^2.2.0
  timeago: ^3.7.1
  google_sign_in: ^6.2.1
  package_info_plus: ^5.0.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  supabase_flutter: ^2.3.0
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.2
  lottie: ^3.3.2
  smooth_page_indicator: ^2.0.1
  flutter_local_notifications: ^18.0.1
  app_links: ^6.3.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
